# This pipeline demonstrates setting environment variables using a repository pre-command hook

steps:
  # This example references GIT_SHORT_HASH inside a script
  - label: ":thinking_face: Check the env var exists"
    command: "./check_environment_var.sh"
    env:
      TEST: ${BUILDKITE_COMMIT:0:7}

  - wait: ~

  # This example references GIT_SHORT_HASH directly, so should be escaped 
  # so the agent executing the job fetches from its own environment
  - label: ":white_check_mark: Use the env var somewhere else!"
    command: "buildkite-agent annotate \"**The evaluated environment variable was:** GIT_SHORT_HASH=$$GIT_SHORT_HASH :tada:\""
